### ISSUE TITLE
[Question]: MiniMessage? How to reset a <st>

### ISSUE THREAD

**Issue by LcyDev** [EncryptSL/LiteEco#17]
### What happened?

Neither <r> or <reset> works.
What can i do?

### Plugin Version

1.1.8-SNAPSHOT

### You detected problem on this server platform ?

PurpurMC

**Comment by LcyDev** [comment]
Also hex doesn't work.
I think you don't use minimessage then?

**Comment by EncryptSL** [comment]
I recommended see this issue #15

Minimessage is used by default in class [ModernText.kt#L19](https://github.com/EncryptSL/LiteEco/blob/main/src/main/kotlin/encryptsl/cekuj/net/api/objects/ModernText.kt#L19).

Reset is on this tag <reset>

Hex is supported by this format 
```YAML 
<color:#your_color>Blah blah</color>
```
Example for hex color this i copy from translation file.
```YAML 
balance_format: "<green>[<white>LITE_ECO<green>] <color:#5e4fa2>Status of balance is</color> <green><money><white> !"
```

**Comment by LcyDev** [comment]
Sorry, i meant hex gradients
https://docs.adventure.kyori.net/minimessage/format.html#gradient

**Comment by EncryptSL** [comment]
Idk from code docs, papermc say, strict mode is by default disabled.
![image](https://user-images.githubusercontent.com/9441083/211845476-0e4d5636-13a2-4a53-bbeb-e3b4ed517f5f.png)

In next build of version, i off this strict mode.
Probably fixed in this commit: https://github.com/EncryptSL/LiteEco/commit/ab22f3bfde55000ced52b2fef02801270ed032ac

Gradients support was added.
In this commit: https://github.com/EncryptSL/LiteEco/commit/c803093f3ee9ae0d5883588adefd23a4a2f126df

Before release of new build i must testing features.

**Comment by EncryptSL** [comment]
New release available [SpigotMC](https://www.spigotmc.org/resources/liteeco-simple-economy-plugin-1-18-x-1-19.101934/updates)

I believe your issue is now solved.
