### ISSUE TITLE
[Question]: Api?

### ISSUE THREAD

**Issue by Pay2Way** [EncryptSL/LiteEco#23]
### Your Question

Hey,

do you have to your econemy plugin, an API where I can query the coins etc. speak with the database? Or do I have to check them myself?

Greetings,
Lao

**Comment by EncryptSL** [comment]
Plugin using VaultAPI and TreasuryAPI, treasury is in alpha version. 

You can use VaultAPI because my plugin is a provider.

Plugin have own api but only for own use, this plugin primary selecting on use VaultAPI, you can use offcourse my own class LiteEcoEconomyAPI, but method like a createAccount using my plugin. If you don't use VaultAPI.

This methods have connect to the database used in my plugin.
From LiteEcoEconomyAPI you can only use this stuff, when u have initialized LiteEcoEconomyAPI and have depend in plugin.yml.
This is example for kotlin.
```KOTLIN
    LiteEcoEconomyAPI#hasAccount(player: OfflinePlayer): Boolean
    LiteEcoEconomyAPI#has(player: OfflinePlayer, amount: Double): Boolean
    LiteEcoEconomyAPI#getBalance(player: OfflinePlayer): Double
    LiteEcoEconomyAPI#depositMoney(player: OfflinePlayer, amount: Double)
    LiteEcoEconomyAPI#withDrawMoney(player: OfflinePlayer, amount: Double)
    LiteEcoEconomyAPI#setMoney(player: OfflinePlayer, amount: Double)
    LiteEcoEconomyAPI#getTopBalance(): MutableMap<String, Double>
```
