### ISSUE TITLE
[Feature Request]: Towny balance gorod = null

### ISSUE THREAD

**Issue by TheMrMes109** [EncryptSL/LiteEco#27]
### Your ideas

When using the plugin for Towny 
in the "/money top list", the balance of cities is displayed in the plugin as null
I would like to be able to turn it off or make it the name of the city

**Comment by EncryptSL** [comment]
This is a know issue, Liteco don't have logic for know if uuid is towny. 

In next release towny be blocked. 
Maybe in future this plugin have support for towny.

**Comment by LlmDl** [comment]
Please consider putting your support behind this PR to Vault: https://github.com/MilkBowl/VaultAPI/pull/138

Your database is keyed entirely by UUIDs which is how Vault should also work primarily. 

My pull request would make it so that plugins like yours which do not properly use the deprecated Vault String methods will be able to work with Towny, Factions, other plugins.
