### ISSUE TITLE
[Feature Request]: Balance limit

### ISSUE THREAD

**Issue by iRazvan2745** [EncryptSL/LiteEco#72]
### Your ideas

A limit to how much a player can send at once, a cooldown for paying people, and a frikin balance limit  just look at [this](https://iraz.insane.rip/📸/u7j555wb.png)

**Comment by EncryptSL** [comment]
Balance limit was added, in next release. https://github.com/EncryptSL/LiteEco/commit/5cf4af96ad1fd7d899e1e06a08e3195d9cefe4ec

Cooldown not implemented maybe in future. ?!
- I don't think if this feature will be implemented.

Balance Limit is implemented, in commands, vault service, this means other plugins hooked into vault respect limit. When account sync is synchronized with database limit is controled too. Features can be disabled in config or by bypass permission.

I can't limit console, because console have full access, if someone want block bypass for operators and players with full permissions to lite eco, must add negative permissions `lite.eco.admin.bypass.limit`

Limit is by default enabled, but in my opinion this is killer of servers but on other side you can hold economy in stability.
